# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "talib_ruby"
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Valentin Treu"]
  s.date = "2013-06-21"
  s.description = "Ruby Wrapper for the Technical Analysis Library ta-lib"
  s.email = "rivella50@gmail.com"
  s.extensions = ["ext/talib/extconf.rb", "ext/talib/extconf.rb"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "example/ma.rb",
    "ext/talib/talib.c",
    "lib/talib_ruby.rb"
  ]
  s.homepage = "http://github.com/rivella50/talib-ruby"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Ruby Wrapper for ta-lib"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

